services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: sparked-next-dev
    environment:
      - WATCHPACK_POLLING=true
      - MONGODB_URI=mongodb://mongodb:27017/sparked-next
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongodb

  prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: sparked-next
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
