import { TProcessCode } from 'types/navigation';

//7000 - 7499
const PAGE_ACTIONS_PROCESS_CODES = {
  PAGE_ACTION_EXIST: 7000,
  PAGE_ACTION_NOT_FOUND: 7001,
  PAGE_ACTION_EDITED: 7002,
  PAGE_ACTION_CREATED: 7003,
  PAGE_ACTION_DELETED: 7004,
} satisfies TProcessCode;

export default PAGE_ACTIONS_PROCESS_CODES;
