FROM node:20 AS base
WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

FROM node:20-alpine3.19 as release
WORKDIR /app

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next
COPY --from=base /app/src ./src
COPY --from=base /app .

EXPOSE 3000

CMD ["yarn", "dev"]