FROM node:22 AS base
WORKDIR /app
COPY package.json yarn.lock ./

RUN yarn install

COPY . .
RUN npm rebuild realm
RUN npm run build

FROM node:22-alpine3.19 as release
WORKDIR /app

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next

EXPOSE 3000

CMD ["yarn", "start"]