name: Check code sanity

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn v4 (Berry)
        run: corepack enable && corepack prepare yarn@4.6.0 --activate

      - name: Cache Yarn v4
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check for existing lockfile
        id: check-lockfile
        run: |
          if [ -f yarn.lock ]; then
            echo "lockfile-exists=true" >> $GITHUB_ENV
          else
            echo "lockfile-exists=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          if [ "$lockfile_exists" == "true" ]; then
            yarn install --immutable --immutable-cache --check-cache
          else
            yarn install
          fi
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false # Allows compatibility with public PRs

      - name: Set environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "MONGODB_DB=sparked-next" >> .env

      - name: Run linter
        run: yarn lint

      - name: Build Next.js app
        run: yarn build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          MONGODB_DB: ${{ secrets.MONGODB_DB }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          REALM_APP_ID: ${{ secrets.REALM_APP_ID }}
